services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 4433:1433
    environment:
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Th3-mustached-yak